"""Add student fields and issue code

Revision ID: 2f507bc56024
Revises: f81ce0a43fbd
Create Date: 2026-03-03 12:49:19.754016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f507bc56024'
down_revision = 'f81ce0a43fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issued_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue_code', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_issued_books_issue_code'), ['issue_code'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roll_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('division', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_roll_number'), ['roll_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_roll_number'))
        batch_op.drop_column('semester')
        batch_op.drop_column('department')
        batch_op.drop_column('division')
        batch_op.drop_column('phone')
        batch_op.drop_column('roll_number')

    with op.batch_alter_table('issued_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issued_books_issue_code'))
        batch_op.drop_column('issue_code')

    # ### end Alembic commands ###
